import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pinput/pinput.dart';
import 'package:otp/otp.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../Widgets/buttonWidget.dart';
import '../providers/security_provider.dart';
import 'recovery_codes_screen.dart';

class Verify2FAScreen extends ConsumerStatefulWidget {
  final String secret;

  const Verify2FAScreen({
    super.key,
    required this.secret,
  });

  @override
  ConsumerState<Verify2FAScreen> createState() => _Verify2FAScreenState();
}

class _Verify2FAScreenState extends ConsumerState<Verify2FAScreen> {
  final _pinController = TextEditingController();
  final _focusNode = FocusNode();
  bool _isLoading = false;
  String? _errorText;

  @override
  void dispose() {
    _pinController.dispose();
    _focusNode.dispose();
    super.dispose();
  }

  bool _verifyCode(String code) {
    try {
      // Check current window, previous window, and next window (±30s)
      final now = DateTime.now().millisecondsSinceEpoch;

      final current = OTP.generateTOTPCodeString(
        widget.secret,
        now,
        length: 6,
        interval: 30,
        algorithm: Algorithm.SHA1,
        isGoogle: true, // Google Authenticator uses Base32 secret
      );

      final prev = OTP.generateTOTPCodeString(
        widget.secret,
        now - 30000,
        length: 6,
        interval: 30,
        algorithm: Algorithm.SHA1,
        isGoogle: true,
      );

      final next = OTP.generateTOTPCodeString(
        widget.secret,
        now + 30000,
        length: 6,
        interval: 30,
        algorithm: Algorithm.SHA1,
        isGoogle: true,
      );

      return code == current || code == prev || code == next;
    } catch (e) {
      debugPrint('Error validating TOTP: $e');
      return false;
    }
  }

  Future<void> _handleVerify() async {
    final code = _pinController.text;
    if (code.length != 6) return;

    setState(() {
      _isLoading = true;
      _errorText = null;
    });

    // Small delay for UX
    await Future.delayed(const Duration(milliseconds: 500));

    if (_verifyCode(code)) {
      try {
        final notifier = ref.read(securitySettingsProvider.notifier);
        await notifier.setTwoFactorEnabled(
          true,
          secret: widget.secret,
        );

        // Generate recovery codes
        final codes = await notifier.generateAndStoreRecoveryCodes();

        if (!mounted) return;

        // Success! Go to recovery codes screen
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (context) => RecoveryCodesScreen(codes: codes),
          ),
        );
      } catch (e) {
        if (!mounted) return;
        setState(() {
          _isLoading = false;
          _errorText = 'Failed to enable 2FA. Please try again.';
        });
      }
    } else {
      setState(() {
        _isLoading = false;
        _errorText = 'Invalid verification code. Please try again.';
        _pinController.clear();
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final defaultPinTheme = PinTheme(
      width: 56,
      height: 60,
      textStyle: AppTextStyles.titleLarge(context).copyWith(
        color: Colors.white,
      ),
      decoration: BoxDecoration(
        color: AppColors.backgroundCard,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.white.withValues(alpha: 0.1)),
      ),
    );

    return Scaffold(
      backgroundColor: AppColors.backgroundDark,
      appBar: AppBar(
        backgroundColor: AppColors.backgroundDark,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.textPrimary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Verify 2FA Setup',
          style: AppTextStyles.titleLarge(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Icon(
              Icons.security_outlined,
              size: 80,
              color: AppColors.primaryOrange,
            ),
            const SizedBox(height: 32),
            Text(
              'Enter the 6-digit code',
              style: AppTextStyles.titleMedium(context).copyWith(
                fontWeight: FontWeight.bold,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Text(
              'Enter the code generated by your authenticator app to confirm setup.',
              style: AppTextStyles.bodyMedium(context).copyWith(
                color: AppColors.textSecondary,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 48),
            Center(
              child: Pinput(
                length: 6,
                controller: _pinController,
                focusNode: _focusNode,
                defaultPinTheme: defaultPinTheme,
                focusedPinTheme: defaultPinTheme.copyWith(
                  decoration: defaultPinTheme.decoration!.copyWith(
                    border: Border.all(color: AppColors.primaryOrange),
                  ),
                ),
                errorPinTheme: defaultPinTheme.copyWith(
                  decoration: defaultPinTheme.decoration!.copyWith(
                    border: Border.all(color: AppColors.error),
                  ),
                ),
                onCompleted: (_) => _handleVerify(),
                autofocus: true,
              ),
            ),
            if (_errorText != null) ...[
              const SizedBox(height: 24),
              Text(
                _errorText!,
                style: AppTextStyles.bodySmall(context).copyWith(
                  color: AppColors.error,
                ),
                textAlign: TextAlign.center,
              ),
            ],
            const SizedBox(height: 48),
            Buttonwidget(
              signText: _isLoading ? 'Verifying...' : 'Verify & Enable',
              onPressed: _isLoading ? () {} : _handleVerify,
            ),
            const SizedBox(height: 24),
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: Text(
                'Cancel Setup',
                style: TextStyle(color: AppColors.textSecondary),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
